# Default values for cloudflared.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  repository: cloudflare/cloudflared
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: 2020.7.3

argo:
  tunnels:
    - hostname: foo.example.com
      url: "http://localhost:8080"

# the chart is expecting an existing Secret resource named as the fqdn
# to be served, with a "cert.pem" data entry in it...
#
# $ kubectl create secret generic foo.example.com --from-file=cert.pem
#
# or even better, a SealedSecrets generated one (gitops style)
#