{{- range $tunnel := .Values.argo.tunnels }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunnel-{{ $tunnel.hostname | b64enc | lower }}
spec:
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: tunnel-{{ $tunnel.hostname | b64enc | lower }}
  template:
    metadata:
        labels:
          app: tunnel-{{ $tunnel.hostname | b64enc | lower }}
    spec:
      containers:
        - name: tunnel-{{ $tunnel.hostname | b64enc | lower }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          args:
          - tunnel
          - --no-autoupdate
          env:
          - name: TUNNEL_URL
            value: {{ $tunnel.url }}
          - name: TUNNEL_HOSTNAME
            value: {{ $tunnel.hostname }}
          # FIXME: liveness probe
          # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-command
          # 
          volumeMounts:
          - mountPath: /etc/cloudflared
            name: tunnel-certificate
            readOnly: true
      volumes:
      - name: tunnel-certificate
        secret:
          secretName: {{ $tunnel.hostname }}
{{- end }}
